### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by bjo81** [ffrl/ff-tools#1]
Hi,
fastdtop crashes here:

Traceback (most recent call last):
  File "./fastdtop.py", line 198, in <module>
    App.run()
  File "/usr/local/lib/python2.7/dist-packages/npyscreen-4.7.2-py2.7.egg/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.**remove_argument_call_main)
  File "/usr/local/lib/python2.7/dist-packages/npyscreen-4.7.2-py2.7.egg/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/usr/local/lib/python2.7/dist-packages/npyscreen-4.7.2-py2.7.egg/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)  
  File "/usr/local/lib/python2.7/dist-packages/npyscreen-4.7.2-py2.7.egg/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/usr/local/lib/python2.7/dist-packages/npyscreen-4.7.2-py2.7.egg/npyscreen/apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "/usr/local/lib/python2.7/dist-packages/npyscreen-4.7.2-py2.7.egg/npyscreen/fm_form_edit_loop.py", line 47, in edit
    self.edit_loop()
  File "/usr/local/lib/python2.7/dist-packages/npyscreen-4.7.2-py2.7.egg/npyscreen/fm_form_edit_loop.py", line 38, in edit_loop
    self._widgets**[self.editw].edit()
  File "/usr/local/lib/python2.7/dist-packages/npyscreen-4.7.2-py2.7.egg/npyscreen/wgtitlefield.py", line 117, in edit
    self.entry_widget.edit()
  File "/usr/local/lib/python2.7/dist-packages/npyscreen-4.7.2-py2.7.egg/npyscreen/wgtextbox.py", line 383, in edit
    self.get_and_use_key_press()
  File "/usr/local/lib/python2.7/dist-packages/npyscreen-4.7.2-py2.7.egg/npyscreen/wgwidget.py", line 550, in get_and_use_key_press
    return self.try_while_waiting()
  File "/usr/local/lib/python2.7/dist-packages/npyscreen-4.7.2-py2.7.egg/npyscreen/wgwidget.py", line 532, in try_while_waiting
    self.parent.while_waiting()
  File "./fastdtop.py", line 158, in while_waiting
    if peer_obj["connection"]["mac_addresses"][0]:
IndexError: list index out of range

**Comment by CyrusOtter** [comment]
Fixed by latest commit, thanks for the bug report :)
